spring:
  datasource:
    url: jdbc:h2:mem:cs;MODE=mysql
    username: admin
    password: admin@1234
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  # spring mvc url 패턴 매칭 기법으로 2.6.x 부터
  # PATH_PATTERN_PARSER가 기본값으로 변경 되어 Swagger 연동 부분에서 오류 발생하여 ant_path_matcher로 수정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging.level:
  org.hibernate.SQL: debug
